/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 unseen.glb --types 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    SM_Architecture: THREE.Mesh
    SM_Wall: THREE.Mesh
    SM_Ledge: THREE.Mesh
    SM_Stairs: THREE.Mesh
    Arc: THREE.Mesh
    Arc2: THREE.Mesh
    Cube001: THREE.Mesh
    Cube002: THREE.Mesh
  }
  materials: {
    Mat_Water: THREE.MeshStandardMaterial
    Mat_Architecture: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

// 1. Add simTexture to the props
export function Model({ simTexture, ...props }: any) {
  const { nodes, materials } = useGLTF('/unseen.glb') as GLTFResult

  return (
    <group {...props} dispose={null}>
      {/* THE WATER FLOOR: Using the physics texture to move Blender vertices */}
      <mesh geometry={nodes.SM_Architecture.geometry}>
        <shaderMaterial
          {...FloorRippleShader}
          uniforms-tSimulation-value={simTexture}
        />
      </mesh>

      {/* STATIC ARCHITECTURE */}
      <mesh geometry={nodes.SM_Stairs.geometry} material={materials.Mat_Architecture} />
      <mesh geometry={nodes.SM_Wall.geometry} material={materials.Mat_Architecture} />
      {/* ... rest of your meshes */}
    </group>
  )
}

useGLTF.preload('/unseen.glb')
