/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 unseen.glb --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    SM_Architecture: THREE.Mesh
    SM_Wall: THREE.Mesh
    SM_Ledge: THREE.Mesh
    SM_Stairs: THREE.Mesh
  }
  materials: {
    Mat_Water: THREE.MeshStandardMaterial
    Mat_Architecture: THREE.MeshStandardMaterial
    Mat_Architecture: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/unseen.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.SM_Architecture.geometry} material={materials.Mat_Water} />
      <mesh geometry={nodes.SM_Wall.geometry} material={materials.Mat_Architecture} />
      <mesh geometry={nodes.SM_Ledge.geometry} material={materials.Mat_Architecture} />
      <mesh geometry={nodes.SM_Stairs.geometry} material={materials.Mat_Architecture} />
    </group>
  )
}

useGLTF.preload('/unseen.glb')
